package lab3;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class bai1 extends javax.swing.JFrame {

    /**
     * Creates new form demotrochoiochu
     */
    public bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tong = new javax.swing.JPanel();
        tren = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        duoi = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        giua = new javax.swing.JPanel();
        phim15 = new javax.swing.JButton();
        phim14 = new javax.swing.JButton();
        phim13 = new javax.swing.JButton();
        phim12 = new javax.swing.JButton();
        phim11 = new javax.swing.JButton();
        phim10 = new javax.swing.JButton();
        phim9 = new javax.swing.JButton();
        phim8 = new javax.swing.JButton();
        phim7 = new javax.swing.JButton();
        phim6 = new javax.swing.JButton();
        phim5 = new javax.swing.JButton();
        phim4 = new javax.swing.JButton();
        phim3 = new javax.swing.JButton();
        phim2 = new javax.swing.JButton();
        phim1 = new javax.swing.JButton();
        phim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tong.setLayout(new java.awt.BorderLayout());

        tren.setBackground(new java.awt.Color(0, 204, 51));
        tren.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TRÒ CHƠI XẾP SỐ");
        tren.add(jLabel1);

        tong.add(tren, java.awt.BorderLayout.PAGE_START);

        duoi.setBackground(new java.awt.Color(0, 255, 0));

        jButton1.setText("BẮT ĐẦU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        duoi.add(jButton1);

        tong.add(duoi, java.awt.BorderLayout.PAGE_END);

        giua.setLayout(new java.awt.GridLayout(4, 4));

        phim15.setText("15");
        phim15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phim15ActionPerformed(evt);
            }
        });
        giua.add(phim15);

        phim14.setText("14");
        phim14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phim14ActionPerformed(evt);
            }
        });
        giua.add(phim14);

        phim13.setText("13");
        giua.add(phim13);

        phim12.setText("12");
        phim12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phim12ActionPerformed(evt);
            }
        });
        giua.add(phim12);

        phim11.setText("11");
        giua.add(phim11);

        phim10.setText("10");
        giua.add(phim10);

        phim9.setText("9");
        giua.add(phim9);

        phim8.setText("8");
        phim8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phim8ActionPerformed(evt);
            }
        });
        giua.add(phim8);

        phim7.setText("7");
        giua.add(phim7);

        phim6.setText("6");
        giua.add(phim6);

        phim5.setText("5");
        phim5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phim5ActionPerformed(evt);
            }
        });
        giua.add(phim5);

        phim4.setText("4");
        phim4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phim4ActionPerformed(evt);
            }
        });
        giua.add(phim4);

        phim3.setText("3");
        giua.add(phim3);

        phim2.setText("2");
        giua.add(phim2);

        phim1.setText("1");
        giua.add(phim1);
        giua.add(phim);

        tong.add(giua, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tong, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showInputDialog("Bấm đi mày");// TODO add your handling cjode here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void phim8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phim8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phim8ActionPerformed

    private void phim15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phim15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phim15ActionPerformed

    private void phim14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phim14ActionPerformed

    }//GEN-LAST:event_phim14ActionPerformed

    private void phim12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phim12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phim12ActionPerformed

    private void phim5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phim5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phim5ActionPerformed

    private void phim4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phim4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phim4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel duoi;
    private javax.swing.JPanel giua;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton phim;
    private javax.swing.JButton phim1;
    private javax.swing.JButton phim10;
    private javax.swing.JButton phim11;
    private javax.swing.JButton phim12;
    private javax.swing.JButton phim13;
    private javax.swing.JButton phim14;
    private javax.swing.JButton phim15;
    private javax.swing.JButton phim2;
    private javax.swing.JButton phim3;
    private javax.swing.JButton phim4;
    private javax.swing.JButton phim5;
    private javax.swing.JButton phim6;
    private javax.swing.JButton phim7;
    private javax.swing.JButton phim8;
    private javax.swing.JButton phim9;
    private javax.swing.JPanel tong;
    private javax.swing.JPanel tren;
    // End of variables declaration//GEN-END:variables
}
