/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Baitap;
import Demo.NewJFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ASUS
 */
public class Lab1 extends javax.swing.JFrame {

    /**
     * Creates new form Lab1
     */
    public Lab1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelChinh = new javax.swing.JPanel();
        PanelTren = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelDuoi = new javax.swing.JPanel();
        PanelGiua = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SupplierID = new javax.swing.JTextField();
        SupplierName = new javax.swing.JTextField();
        Books = new javax.swing.JCheckBox();
        NewPapers = new javax.swing.JCheckBox();
        JournalsandMagazines = new javax.swing.JCheckBox();
        Address = new javax.swing.JTextField();
        ContactNo = new javax.swing.JTextField();
        EmailID = new javax.swing.JTextField();
        Remarks = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Panelluuxoasua = new javax.swing.JPanel();
        New = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelChinh.setLayout(new java.awt.BorderLayout());

        PanelTren.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setBackground(new java.awt.Color(0, 102, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Books Suppliers");
        PanelTren.add(jLabel1);

        PanelChinh.add(PanelTren, java.awt.BorderLayout.PAGE_START);

        PanelGiua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Suppller ID :");

        jLabel3.setText("Supplier Name :");

        jLabel4.setText("Supplier Type :");

        jLabel5.setText("Address :");

        jLabel6.setText("Contact No :");

        jLabel7.setText("Email ID :");

        jLabel8.setText("Remarks :");

        SupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierIDActionPerformed(evt);
            }
        });

        buttonGroup1.add(Books);
        Books.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Books.setText("Books");
        Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksActionPerformed(evt);
            }
        });

        buttonGroup1.add(NewPapers);
        NewPapers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NewPapers.setText("News Papers");

        buttonGroup1.add(JournalsandMagazines);
        JournalsandMagazines.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JournalsandMagazines.setText("Journals and Magazines");
        JournalsandMagazines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JournalsandMagazinesActionPerformed(evt);
            }
        });

        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "                   ", "             ", "                  ", "                   ", "                 " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Remarks.setViewportView(jList1);

        javax.swing.GroupLayout PanelGiuaLayout = new javax.swing.GroupLayout(PanelGiua);
        PanelGiua.setLayout(PanelGiuaLayout);
        PanelGiuaLayout.setHorizontalGroup(
            PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGiuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(52, 52, 52)
                .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGiuaLayout.createSequentialGroup()
                        .addComponent(Books)
                        .addGap(18, 18, 18)
                        .addComponent(NewPapers)
                        .addGap(16, 16, 16)
                        .addComponent(JournalsandMagazines))
                    .addComponent(SupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EmailID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(ContactNo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(Remarks))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGiuaLayout.setVerticalGroup(
            PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGiuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelGiuaLayout.createSequentialGroup()
                        .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(SupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4))
                    .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Books)
                        .addComponent(NewPapers)
                        .addComponent(JournalsandMagazines)))
                .addGap(24, 24, 24)
                .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGiuaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8))
                    .addGroup(PanelGiuaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panelluuxoasua.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        New.setBackground(new java.awt.Color(51, 153, 0));
        New.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        New.setForeground(new java.awt.Color(255, 255, 255));
        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        Save.setBackground(new java.awt.Color(255, 153, 51));
        Save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(0, 153, 153));
        Delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");

        Update.setBackground(new java.awt.Color(204, 0, 102));
        Update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");

        javax.swing.GroupLayout PanelluuxoasuaLayout = new javax.swing.GroupLayout(Panelluuxoasua);
        Panelluuxoasua.setLayout(PanelluuxoasuaLayout);
        PanelluuxoasuaLayout.setHorizontalGroup(
            PanelluuxoasuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelluuxoasuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(36, 36, 36)
                .addComponent(Delete)
                .addGap(40, 40, 40)
                .addComponent(Update)
                .addGap(19, 19, 19))
        );
        PanelluuxoasuaLayout.setVerticalGroup(
            PanelluuxoasuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelluuxoasuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelluuxoasuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New)
                    .addComponent(Save)
                    .addComponent(Delete)
                    .addComponent(Update))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelDuoiLayout = new javax.swing.GroupLayout(PanelDuoi);
        PanelDuoi.setLayout(PanelDuoiLayout);
        PanelDuoiLayout.setHorizontalGroup(
            PanelDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDuoiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PanelDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelGiua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panelluuxoasua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        PanelDuoiLayout.setVerticalGroup(
            PanelDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDuoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGiua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panelluuxoasua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelChinh.add(PanelDuoi, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

        Connection conn= null;
        String url = "jdbc:jtds:sqlserver://localhost:1433/Books Suppliers [sa on dbo]";
        String user= "sa";
        String password = "123";
        String sql = "INSERT INTO Employee"+"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, )";
        
        PreparedStatement preStmt= null;
        String strSupID = SupplierID.getText();
        String strName = SupplierName.getText();
         int row=0;
        String strType = "";
        String strAddress = Address.getText();
        String strContact = ContactNo.getText();
        String strEmail = EmailID.getText();
        String strremark = Remarks.getName();
        
   
        
        if (Books.isSelected()==true) {
            strType="Books";
        }else if (NewPapers.isSelected()==true){
            strType="New Paper";
        }else if (JournalsandMagazines.isSelected()==true) {
            strType="Journals and Magazines";          
        }
        
        
        try {   
           
        
            conn = DriverManager.getConnection(url, user, password);
            preStmt = conn.prepareStatement(sql);
            preStmt.setString(1, strSupID);
            preStmt.setString(2, strName);
            preStmt.setString(3, strType);
            preStmt.setString(4, strAddress);
            preStmt.setString(5, strContact);
            preStmt.setString(5, strEmail);
            preStmt.setString(5, strremark);
            row = preStmt.executeUpdate();
            System.out.println("Row inserted"+row);
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         
        
    }//GEN-LAST:event_SaveActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BooksActionPerformed

    private void SupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierIDActionPerformed

    private void JournalsandMagazinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JournalsandMagazinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JournalsandMagazinesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JCheckBox Books;
    private javax.swing.JTextField ContactNo;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField EmailID;
    private javax.swing.JCheckBox JournalsandMagazines;
    private javax.swing.JButton New;
    private javax.swing.JCheckBox NewPapers;
    private javax.swing.JPanel PanelChinh;
    private javax.swing.JPanel PanelDuoi;
    private javax.swing.JPanel PanelGiua;
    private javax.swing.JPanel PanelTren;
    private javax.swing.JPanel Panelluuxoasua;
    private javax.swing.JScrollPane Remarks;
    private javax.swing.JButton Save;
    private javax.swing.JTextField SupplierID;
    private javax.swing.JTextField SupplierName;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    // End of variables declaration//GEN-END:variables
}
