/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab2;

/**
 *
 * @author USER
 */
public class Bai1 extends javax.swing.JFrame {

    /**
     * Creates new form Bai2
     */
    public Bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        hienthi = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        so1 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        dauchia = new javax.swing.JButton();
        can2 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        daunhan = new javax.swing.JButton();
        phantram = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        dautru = new javax.swing.JButton();
        phanso = new javax.swing.JButton();
        so0 = new javax.swing.JButton();
        conghoactru = new javax.swing.JButton();
        chuC = new javax.swing.JButton();
        daucong = new javax.swing.JButton();
        daubang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        hienthi.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienthi, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienthi, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(4, 5));

        so1.setText("1");
        so1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel4.add(so1);

        so2.setText("2");
        so2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so2ActionPerformed(evt);
            }
        });
        jPanel4.add(so2);

        so3.setText("3");
        so3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so3ActionPerformed(evt);
            }
        });
        jPanel4.add(so3);

        dauchia.setText("/");
        dauchia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dauchiaActionPerformed(evt);
            }
        });
        jPanel4.add(dauchia);

        can2.setText("Sqrt");
        can2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can2ActionPerformed(evt);
            }
        });
        jPanel4.add(can2);

        so4.setText("4");
        so4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so4ActionPerformed(evt);
            }
        });
        jPanel4.add(so4);

        so5.setText("5");
        so5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so5ActionPerformed(evt);
            }
        });
        jPanel4.add(so5);

        so6.setText("6");
        so6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so6ActionPerformed(evt);
            }
        });
        jPanel4.add(so6);

        daunhan.setText("*");
        daunhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daunhanActionPerformed(evt);
            }
        });
        jPanel4.add(daunhan);

        phantram.setText("%");
        phantram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phantramActionPerformed(evt);
            }
        });
        jPanel4.add(phantram);

        so7.setText("7");
        so7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so7ActionPerformed(evt);
            }
        });
        jPanel4.add(so7);

        so8.setText("8");
        so8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so8ActionPerformed(evt);
            }
        });
        jPanel4.add(so8);

        so9.setText("9");
        so9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so9ActionPerformed(evt);
            }
        });
        jPanel4.add(so9);

        dautru.setText("-");
        dautru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dautruActionPerformed(evt);
            }
        });
        jPanel4.add(dautru);

        phanso.setText("1/x");
        jPanel4.add(phanso);

        so0.setText("0");
        so0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so0ActionPerformed(evt);
            }
        });
        jPanel4.add(so0);

        conghoactru.setText("+/-");
        conghoactru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conghoactruActionPerformed(evt);
            }
        });
        jPanel4.add(conghoactru);

        chuC.setText("C");
        chuC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuCActionPerformed(evt);
            }
        });
        jPanel4.add(chuC);

        daucong.setText("+");
        daucong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daucongActionPerformed(evt);
            }
        });
        jPanel4.add(daucong);

        daubang.setText("=");
        daubang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daubangActionPerformed(evt);
            }
        });
        jPanel4.add(daubang);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void so1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so1ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12)
            if(gt.equals("0"));
                long so = Long.parseLong(gt +so1.getText());
                this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so1ActionPerformed

    private void so2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so2ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
            if(gt.equals("0"));
            long so = Long.parseLong(gt +so2.getText());
            this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so2ActionPerformed

    private void so3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so3ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
        if(gt.equals("0"));
        long so = Long.parseLong(gt +so3.getText());
        this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so3ActionPerformed

    private void so4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so4ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
        if(gt.equals("0"));
        long so = Long.parseLong(gt +so4.getText());
        this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so4ActionPerformed

    private void so5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so5ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
            if(gt.equals("0"));
            long so = Long.parseLong(gt +so5.getText());
            this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so5ActionPerformed

    private void so6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so6ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
        if(gt.equals("0"));
        long so = Long.parseLong(gt +so6.getText());
        this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so6ActionPerformed

    private void so7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so7ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
        if(gt.equals("0"));
        long so = Long.parseLong(gt +so7.getText());
        this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so7ActionPerformed

    private void so8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so8ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
            if(gt.equals("0"));
            long so = Long.parseLong(gt +so8.getText());
            this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so8ActionPerformed

    private void so9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so9ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
        if(gt.equals("0"));
        long so = Long.parseLong(gt +so9.getText());
        this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so9ActionPerformed

    private void so0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so0ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienthi.getText();
        if(gt.length()<12);
        if(gt.equals("0"));
        long so = Long.parseLong(gt +so0.getText());
        this.hienthi.setText(String.valueOf(so));
    }//GEN-LAST:event_so0ActionPerformed

    private void dauchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dauchiaActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienthi.getText());
        if(this.a !=0){
            this.pheptoan = "/";
            this.hienthi.setText("");
        }
    }//GEN-LAST:event_dauchiaActionPerformed

    private void daunhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daunhanActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienthi.getText());
        this.pheptoan ="*";
        this.hienthi.setText("");
    }//GEN-LAST:event_daunhanActionPerformed

    private void dautruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dautruActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienthi.getText());
        this.pheptoan = "-";
        this.hienthi.setText("");
    }//GEN-LAST:event_dautruActionPerformed

    private void daucongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daucongActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienthi.getText());
        this.pheptoan = "+";
        this.hienthi.setText("");
    }//GEN-LAST:event_daucongActionPerformed

    private void daubangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daubangActionPerformed
        // TODO add your handling code here:
        if(this.pheptoan.length()>0){
            long b = Long.parseLong(this.hienthi.getText());
            if(this.pheptoan.equals("+")){
                long kq = this.a + b;
                this.hienthi.setText(String.valueOf(kq));
            }
            else if(this.pheptoan.equals("-")){
                long kq = this.a - b;
                this.hienthi.setText(String.valueOf(kq));
            }
            else if(this.pheptoan.equals("*")){
                long kq = this.a * b;
                this.hienthi.setText(String.valueOf(kq));
            }
            else if(this.pheptoan.equals("/")){
                long kq = this.a / b;
                this.hienthi.setText(String.valueOf(kq));
            }
            else if(this.pheptoan.equals("%")){
                long kq = this.a % b;
            }
        }
    }//GEN-LAST:event_daubangActionPerformed

    private void can2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can2ActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienthi.getText());
        this.pheptoan ="sqrt";
        this.hienthi.setText("1.41421");
    }//GEN-LAST:event_can2ActionPerformed

    private void phantramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phantramActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_phantramActionPerformed

    private void chuCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuCActionPerformed
        // TODO add your handling code here:
        this.hienthi.setText("0");
    }//GEN-LAST:event_chuCActionPerformed

    private void conghoactruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conghoactruActionPerformed
        // TODO add your handling code here:
       this.a = Long.parseLong(String.valueOf(hienthi.getText()));
       this.pheptoan ="-";
       this.hienthi.setText(pheptoan);
    }//GEN-LAST:event_conghoactruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton can2;
    private javax.swing.JButton chuC;
    private javax.swing.JButton conghoactru;
    private javax.swing.JButton daubang;
    private javax.swing.JButton dauchia;
    private javax.swing.JButton daucong;
    private javax.swing.JButton daunhan;
    private javax.swing.JButton dautru;
    private javax.swing.JLabel hienthi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton phanso;
    private javax.swing.JButton phantram;
    private javax.swing.JButton so0;
    private javax.swing.JButton so1;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    // End of variables declaration//GEN-END:variables
    private long a = 0;
    private String pheptoan="";
}
